### ISSUE TITLE
Feature Request: Add an option to reverse the process of splitting

### ISSUE THREAD

**Issue by noveoko** [whiplashoo/split-image#1]
It would be very useful if the script allowed me to reverse the process of splitting by joining the processed tiles back together.

**Comment by whiplashoo** [comment]
Version 1.2.0 adds this feature. You can now use the -r flag to reverse the split process and merge multiple image tiles into one:

`split-image cat.jpg 2 2 -r`

Will attempt to merge similarly named image tiles to one image. So, if you have these images in the current directory:

* `cat_0.jpg`
* `cat_1.jpg`
* `cat_2.jpg`
* `cat_3.jpg`

they will be merged according to their file name:

<p align="center">
<img width="75%" src="https://user-images.githubusercontent.com/9117427/182033564-514a47c9-f76e-4ee7-9520-7b1dac68f221.png"/>
</p>

You have to take care of the correct file naming and order, for the time being. You can also pass the `--cleanup` flag to remove the original images.
