### ISSUE TITLE
is there a way to use it in python script?

### ISSUE THREAD

**Issue by mcdominik** [whiplashoo/split-image#11]
Hi:) I need to slice my images accordingly to some kind of algorithm, so terminal usage is cumbersome.
Is there a way to do it similar to this pseudocode?

```
from split-image import Slicer

list_of_slices = Slicer('myimage.jpg', rows_num, col_num)

```

**Comment by whiplashoo** [comment]
Hey, thanks for the feedback.

I just pushed an update (v1.6.1) which should let you do this:

```python
from split_image import split_image

split_image(image_path, rows, cols, should_square, should_cleanup, [output_dir])
# e.g. split_image("bridge.jpg", 2, 2, True, False)
```

Try it out and let me know!

**Comment by mcdominik** [comment]
Thanks, I installed 1.6.1, but when I try to import the package :

> Import "split_image" could not be resolvedPylance[reportMissingImports]

**Comment by whiplashoo** [comment]
That is probably an issue with your interpreter. Ignore the message and try to run the script. Does it work?

I also have seen the same error when I am using VS Code, and it's because I use the wrong Python interpreter. You can try:

- Cmd+Shift+P > Python> Select Interpreter.
- Select the proper interpreter. For me, it's in homebrew's installation, since pip was installed there.

**Comment by mcdominik** [comment]
You are right, my fault. It was installed in my anaconda interpreter path, I changed it and now it's visible, and works:)
But even when I set flag cleanup=True, there is still copy of my original image with name: '[image]_square.jpeg'. Is there a way to remove this automatically?

**Comment by whiplashoo** [comment]
If you have set the squared flag, the tool also generates its squared version. The clean up flag only removes the original image, as the user may need the squared version. 

If you feel like there should be an additional option for removing the squared image too, feel free to open a new issue!
