### ISSUE TITLE
Output directory format

### ISSUE THREAD

**Issue by JasperCoyotte** [whiplashoo/split-image#17]
Hello
I want to split an image and place the result in a Split directory.
My script
```
import cv2
from split_image import split_image

split_image("Eau1_gray.jpg",1,8, False, False, |'Split'])

cv2.waitKey(0)
cv2.destroyAllWindows()
```
do not work. Split is OK but in the current directory

**Comment by whiplashoo** [comment]
The correct call would be:
```python
split_image("Eau1_gray.jpg", 1, 8, False, False, 'Split')
```
If it doesn't work, please reopen this issue.

**Comment by H-Bey** [comment]
Unfortunately, I am falling in the same issue.
`split_image("Eau1_gray.jpg", 1, 8, False, False, 'Split')`
didn't work!
Output directory is always the default directory!

**Comment by milanvhb** [comment]
Same problem, output dir seems broken
