### ISSUE TITLE
Doesn't work on Jupyter notebooks

### ISSUE THREAD

**Issue by WangariKimotho** [whiplashoo/split-image#2]
I have tested the code on terminal and the package works as expected and with given example. The only issue so far is that the same code doesn't work on jupyter notebook.

**Comment by whiplashoo** [comment]
I have not tried this for Jupyter notebooks. Could you share an example notebook, so I can check how it might work?

**Comment by WangariKimotho** [comment]
![image](https://user-images.githubusercontent.com/75425505/175915653-c07d8f24-1f99-40fb-a011-4305b6f49113.png)
This is the error.
I was wondering if perhaps it has to do with the fact that there is actually no importation taking place eg  'import split_image'. Cuz I'm using this in a jupyter notebook on an python3 kernel.

**Comment by WangariKimotho** [comment]
![image](https://user-images.githubusercontent.com/75425505/175926817-806601d2-70e1-4758-97ee-25fe036f66cb.png)

I worked it out by running the code as a shell command(my bad).
