### ISSUE TITLE
Feature Request: Batch Processing & Directory Saving

### ISSUE THREAD

**Issue by megrimm** [whiplashoo/split-image#3]
Anyway to batch process/split images? Saving splits to a different directory?

Maybe there is an easy way to do this already by piping filenames to "split-image"?

Thanks!

- [ ] Batch processing multiple images

- [x] Set a custom output directory

**Comment by whiplashoo** [comment]
In v1.5.0, added the ability to set a custom output directory for the image tiles. 

Usage: `split-image test.jpg 2 2 --output-dir <dir-name>`

Stay tuned for the batch processing feature

**Comment by whiplashoo** [comment]
In v2.0.0, you can now set a directory as the image path. So, for example:

`split-image . 2 2` will split all images in the current folder, or

`split-image image_dir 2 2 --output-dir outp` will split all images in the `image_dir` folder and output the result in the `outp` folder.
